### ISSUE TITLE
Documents

### ISSUE THREAD

**Issue by imflash217** [imflash217/Lumos#1]
[Java_TheCompleteReference-HerbertSchildt.pdf](https://github.com/vinaykumar2491/Lumos/files/95405/Java_TheCompleteReference-HerbertSchildt.pdf)

**Comment by vinaykumar2491** [comment]
[patterson_book.pdf](https://github.com/vinaykumar2491/Lumos/files/95453/patterson_book.pdf)

**Comment by vinaykumar2491** [comment]
[William Stallings - Computer Organization and Architecture 8-edn.pdf](https://github.com/vinaykumar2491/Lumos/files/95454/William.Stallings.-.Computer.Organization.and.Architecture.8-edn.pdf)

**Comment by vinaykumar2491** [comment]
- [ ] do it
